### ISSUE TITLE
carma sim vehicle attempts to follow route and crashes into map

### ISSUE THREAD

**Issue by adev4a** [usdot-fhwa-stol/carma-carla-integration#14]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

![image](https://user-images.githubusercontent.com/51463994/206458078-49d51be9-ab62-4c28-9a5a-3492a2a277d6.png)

carma-sim vehicle crashes into the map while seemingly attempting to follow route.
It is seen that most ros topics stop publishing any data when this happens, however the containers remain active and an echo request can be sent on the topics.
trajectory_executor continuously publishes successfully swapped trajectories which should be happen on each new trajectory plan.
Terminal output shows trajectory plans being published are empty.
![image](https://user-images.githubusercontent.com/51463994/206330834-fbf94a3c-0636-4d2f-a834-57828c0b93d1.png)

### Carma version where this issue was discovered

Using  usdotfhwastol/carma-config:carma-system-4.2.0-xil-cloud-test.

### Expected behavior
carma sim is launched with an engaged carma vehicle which is able to complete the set route.

### Actual behavior

carma vehicle in sim crashes into map.

### Steps to reproduce the actual behavior

1. Start carma-cloud sim
2. At time of reporting issue is seen 1/5 times.

**Comment by chengyuan0124** [comment]
This issue will be fix by adjusting [inlanecruising config](https://github.com/usdot-fhwa-stol/carma-platform/blob/563538a7952626a9de8f8a44441c297a3485bcd9/inlanecruising_plugin/config/parameters.yaml#L10-L11)
