### ISSUE TITLE
carma-carla-integration has roslaunch syntax errors

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-carla-integration#31]
### Summary

carma-carla-1.1.0 (and develop) has a roslaunch syntax error at

https://github.com/usdot-fhwa-stol/carma-carla-integration/blob/carma-simulation-1.1.0/carma-carla-integration/carma-carla-agent/launch/carma_carla_agent.launch#L34

and

https://github.com/usdot-fhwa-stol/carma-carla-integration/blob/develop/carma-carla-integration/carma-carla-agent/agent/bridge.launch#L89

Unable to determine if these launch syntax errors are critical at the moment because the team has been using the repo without any issue for a while
### Version

4.3.0 (Current)

### Expected Behavior

carma-carla-integration should start without shutting down.

### Actual Behavior

carma-carla-integration-1.1.0 shuts down on startup, but it could be due to a different issue of python versions

### Steps to Reproduce the Actual Behavior

follow instruction at 
https://usdot-carma.atlassian.net/wiki/spaces/CRMSIM/pages/2419916803/Setup+Instructions+Documentation+CARMA-CARLA+integration

**Comment by chengyuan0124** [comment]
It has be addressed from this [PR](https://github.com/usdot-fhwa-stol/carma-carla-integration/pull/33) and merged to the develop branch
